import cv2
import numpy as np
import sys

src = cv2.imread('baboon.jpg',cv2.IMREAD_COLOR)
cv2.namedWindow("Original image")
cv2.imshow("Original image", src)

b,g,r = cv2.split(src)
cv2.namedWindow("Red")
cv2.imshow("Red",r)
cv2.namedWindow("Green")
cv2.imshow("Green",g)
cv2.namedWindow("Blue")
cv2.imshow("Blue",b)

hsv = cv2.cvtColor(src, cv2.COLOR_BGR2HSV)
H,S,V = cv2.split(hsv)
cv2.namedWindow("H")
cv2.imshow("H",H)
cv2.namedWindow("S")
cv2.imshow("S",S)
cv2.namedWindow("V")
cv2.imshow("V",V)

ycc = cv2.cvtColor(src, cv2.COLOR_BGR2YCrCb)
Y,Cr,Cb = cv2.split(ycc)
cv2.namedWindow("Y")
cv2.imshow("Y",Y)
cv2.namedWindow("Cr")
cv2.imshow("Cr",Cr)
cv2.namedWindow("Cb")
cv2.imshow("Cb",Cb)

yuv = cv2.cvtColor(src, cv2.COLOR_BGR2YUV)
Y1,U,V1 = cv2.split(yuv)
cv2.namedWindow("Y of YUV")
cv2.imshow("Y of YUV",Y1)
cv2.namedWindow("U")
cv2.imshow("U",U)
cv2.namedWindow("V of YUV")
cv2.imshow("V of YUV",V1)

hls = cv2.cvtColor(src, cv2.COLOR_BGR2HLS)
H1,L,S1 = cv2.split(hls)
cv2.namedWindow("Hue")
cv2.imshow("Hue",H1)
cv2.namedWindow("Luminance of HLS")
cv2.imshow("Luminance of HLS",L)
cv2.namedWindow("Saturation")
cv2.imshow("Saturation",S1)

lab = cv2.cvtColor(src, cv2.COLOR_BGR2Lab)
L1,A,B = cv2.split(lab)
cv2.namedWindow("Luminance of Lab")
cv2.imshow("Luminance of Lab",L1)
cv2.namedWindow("A")
cv2.imshow("A",A)
cv2.namedWindow("B")
cv2.imshow("B",B)

print("BGR value: ", src[20,25])
print("HSV value: ", hsv[20,25])
print("YCrCb value: ", ycc[20,25])
cv2.waitKey(0)
cv2.destroyAllWindows()